#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=0.11.9
PACKAGE=fastqc
TOOL=fastqc
DIRECTORY=~/Documents/fastqc_demo/software/fastqc
STORAGE=/home/

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
